### ISSUE TITLE
No option to go back to the previous music.

### ISSUE THREAD

**Issue by rajarahulray** [talwat/lowfi#36] opened 2024-10-16 15:01 UTC
Hi @talwat ,
I am currently using the lowfi and I pretty much love its simplicity and controls.
However, I don't see any option to go back to the previous music/melody.

Is it possible to add that option in the next release?

Thanks.

**Comment by danielwerg** [comment] 2024-10-16 17:56
Seeking is also not implemented but that might be by design.

**Comment by talwat** [comment] 2024-10-16 18:07
> Is it possible to add that option in the next release?

*Possibly*, but you'd only be able to go back one song in this hypothetical. The way I see it being implemented is that lowfi would save only one previous song, so if you wanted to go back *two* songs that'd be impossible.

Also, lowfi is meant for ambient songs, not as a general purpose player. Ambient songs don't need seeking or previous since you don't *really* care about the song itself, just the fact that it calms you down a bit and helps you relax. That's not anything against the artists, they're super talented, but I just don't see enough people wanting this or seeking for it to be considered.

This feature would also be pretty technically demanding, since I'd have to restructure some things because in the code lowfi always assumes that whenever a song is changed it should just go to the "next" song or a different one.

This isn't a wontfix just yet, but try and think if this feature is really important enough to warrant being added. Lowfi, at it's core, is supposed to be simple & specialized for ambient music, and I really would like to keep it that way.

**Comment by talwat** [comment] 2024-10-18 21:43
Well, presuming this has been inactive for two days, I'm assuming this feature wasn't all that important to justify the effort it would take.

Closing as a wontfix.

**Closed by talwat** 2024-10-18 21:43 UTC
Labels: enhancement

**Comment by Gu1llaum-3** [comment] 2025-03-13 13:55
I created a pull request with the possibility of going back if necessary.

https://github.com/talwat/lowfi/pull/73
