### ISSUE TITLE
MPRIS support

### ISSUE THREAD

**Issue by omnigenous** [talwat/lowfi#7] opened 2024-10-02 17:36 UTC
Noticed `lowfi` doesn't use mpv to play audio I realized it probably doesn't support MPRIS. Can't control `lowfi` with keybind binded to `playerctl` command.

**Comment by BrendanMesters** [comment] 2024-10-02 18:18
I also noticed this, and was thinking about implementing it. 

@talwat if you want to do this yourself, let me know, but otherwise, I'd be happy to give it a try when I have time (also let me know ;p)

**Comment by talwat** [comment] 2024-10-02 18:43
I think `crossterm` mentioned *something* about this, but I should be able to implement this fairly easily.

@BrendanMesters If you'd like to take a go at it, I'd wait until https://github.com/talwat/lowfi/pull/4 this PR is finished since it has some changes relating to input, so you'd basically have to redo all of your work.

**Comment by BrendanMesters** [comment] 2024-10-02 18:45
It should be as simple as looking for the right create and implementing the interface yeah

**Comment by talwat** [comment] 2024-10-02 18:49
I think crossterm has [some sort of functionality for special keyboard events](https://docs.rs/crossterm/latest/crossterm/event/struct.PushKeyboardEnhancementFlags.html) which could be worth taking a look at. For now, just check #4 to see if my implementation works & you'll be able to work on this.

**Comment by talwat** [comment] 2024-10-02 21:08
@BrendanMesters Consider this the "all clear" for working on this issue. I think I'll likely shift my attention to track sources & downloading, so you can implement this one in a PR and it should be without merge conflicts.

**Comment by talwat** [comment] 2024-10-04 09:26
Well, this has been implemented https://github.com/talwat/lowfi/commit/706ba97428e5d81a19e43127ee1138df1579c07e but I'm hesitant to push it out since I am yet to test it. If it's not too much of a bother, could you try cloning the repo and running lowfi to see if there's any change?

**Comment by omnigenous** [comment] 2024-10-04 09:32
Couldn't find build instructions in README. Can you tell me how to build it?

**Comment by omnigenous** [comment] 2024-10-04 10:05
Works as expected, at first nothing worked because all my media keys were bind to playerctl command in hyprland config. had to unbind them to test this.

Are you not willing to add mpris support? While support media keys alone is a great addition I would like to be able to control lowfi when it's out of focus in another workspace with my media keys that are bound to playerctl commands.

**Comment by omnigenous** [comment] 2024-10-04 10:14
Also I noticed volume media keys change volume by 10 and not 1, is that intentional? I have my lowfi on 3% currently that's why I'm wondering :D

**Comment by talwat** [comment] 2024-10-04 12:12
> Are you not willing to add mpris support? While support media keys alone is a great addition I would like to be able to control lowfi when it's out of focus in another workspace with my media keys that are bound to playerctl commands.

Whoops, I was kind of under the impression MPRIS just sent media keys. I really do want to support it, I was just confused about what it actually is since the documentation just says "support the media keys."

I'll keep this issue open while I do some more research on how I'm actually supposed to implement MPRIS :)

Also, the volume adjustment is probably unintentional, again, I'm a bit of a dumbass 😅

**Comment by omnigenous** [comment] 2024-10-04 12:20
I just know about user aspect of it from [Arch wiki](https://wiki.archlinux.org/title/MPRIS) not sure about implementation, I don't program that much besides simple shell scripts.

**Comment by talwat** [comment] 2024-10-04 12:31
I found [this](https://github.com/SeaDve/mpris-server) library which claims to implement MPRIS, but it's fairly small. I'll see if I can make it work though, but it may take some time.

**Comment by talwat** [comment] 2024-10-05 10:33
Update on this, I can confirm MPRIS support!

Although, it will probably be a compile time option. My reasoning is that dbus is Linux exclusive, so it doesn't make sense to ship it with every install of lowfi. If that's a total deal breaker I can try and compromise, but it's just that it is a bit of a heavy dependency and I would like to retain the "simplicity" part of lowfi.

**Comment by omnigenous** [comment] 2024-10-05 10:39
Could you elaborate on "it will probably be a compile time option"? It shouldn't effect end user right? How I understand, AUR maintainer would just have to change build process slightly and end user won't see the difference.

**Comment by talwat** [comment] 2024-10-05 12:30
Rust supports compilation time features, so you can have some code built only if you're gonna use that feature. That's what I plan to do. Although I think on the AUR I'll have it enabled, since I'm guessing more Arch users have DE's and such that actually support MPRIS.

**Comment by talwat** [comment] 2024-10-05 19:02
I think MPRIS will be supported, but not to a very large degree. Specific features will work, but there are some annoyances with the protocol that prevent granularity. For example, seeking is not supported in lowfi but volume control is.

It might be a bit funky in DE's, which is why I will _also_ not be including it in the AUR. This'll only be accessible if you install via `cargo`.

MPRIS is much more complicated and expansive than I initially thought, and lowfi is supposed to be simple, which is why I'm making this decision.

**Comment by talwat** [comment] 2024-10-05 20:05
Alright, #14 is now a thing.

I think after #14 is merged I'll have to take a serious look at the code and refactor things, since it's becoming spaghetti mess.

`lowfi` already wasn't supposed to take in that many features, so I think I'll probably do configurable sources, a few small misc features, and refactor/bugfix from there.

**Comment by talwat** [comment] 2024-10-06 15:48
Solved with #14.

**Closed by talwat** 2024-10-06 15:48 UTC
Labels: enhancement, in progress

**Comment by omnigenous** [comment] 2024-10-07 18:37
> It might be a bit funky in DE's, which is why I will also not be including it in the AUR. This'll only be accessible if you install via cargo.

This is heartbreaking 😢

Do you still stand by this or something changed? I don't really understand what you mean with it being "funky in DE's", can you explain (I use hyprland and had no mpris issues).

It's wild be quiet tidious to remember update lowfi with cargo for me and many users, versus updating along side with entire system with `yay`.

Have you consider any of this:

1. Have separate yay package for mpris version of lowfi. Publishing to aur could be automated with github action.
2. Have extra package for lowfi that enables supports for lowfi. User would just have to install it and **maybe** change value in lowfi config
3. Add option to config to toggle mpris support. Downside is you ship package with mpris that user **might** never use. So 1 and 2 is better option if that is the case.

**Comment by talwat** [comment] 2024-10-07 19:19
Well, I accidentally included it in the AUR build, so consider that previous statement revoked haha :laughing: 

I'll keep it in for now and see how stable it is. If it causes more issues I'll revert to making it optional, but otherwise I'll keep it as-is.
